on: push

name: Build and Deploy to S3

jobs:
  nPMBuild:
    name: NPM Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chrislennon/action-aws-cli@1.1  # install AWS CLI

    - name: NPM Build
      if: github.ref == 'refs/heads/master'
      env:
        REACT_APP_API_HOST: https://access-api.datastage.io
        REACT_APP_AUTH_HOST: https://gen3.biodatacatalyst.nhlbi.nih.gov
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_REDIRECT_URL: https://access.datastage.io/login
      run: npm ci && npm run build

    - name: QA NPM Build
      if: github.ref != 'refs/heads/master'
      env:
        REACT_APP_API_HOST: https://qa-access-api.planx-pla.net
        REACT_APP_AUTH_HOST: https://staging.gen3.biodatacatalyst.nhlbi.nih.gov
        REACT_APP_CLIENT_ID: ${{ secrets.QA_REACT_APP_CLIENT_ID }}
        REACT_APP_REDIRECT_URL: https://qa-access.planx-pla.net/login
      run: npm ci && npm run build

    - name: TEST NPM Build
      if: github.ref != 'refs/heads/feat/per-user-auth'
      env:
        REACT_APP_API_HOST: https://qa-anvil.planx-pla.net/access-backend
        REACT_APP_AUTH_HOST: https://qa-anvil.planx-pla.net
        REACT_APP_CLIENT_ID: ${{ secrets.TEST_REACT_APP_CLIENT_ID }}
        REACT_APP_REDIRECT_URL: https://access-test.planx-pla.net/login
      run: npm ci && npm run build

    - name: Deploy to S3
      if: github.ref == 'refs/heads/master'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET: access.datastage.io
      run: ls -al; cd build; ls -al; mkdir ../access-art && mv * ../access-art/. && mv ../access-art/* .; aws s3 sync . s3://$BUCKET --delete --acl public-read

    - name: QA Deploy to S3
      if: github.ref != 'refs/heads/master'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
        BUCKET: qa-access.planx-pla.net
      run: ls -al; cd build; ls -al; mkdir ../access-art && mv * ../access-art/. && mv ../access-art/* .; aws s3 sync . s3://$BUCKET --delete --acl public-read

    - name: TEST Deploy to S3
      if: github.ref != 'refs/heads/feat/per-user-auth'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        BUCKET: access-test.planx-pla.net
      run: ls -al; cd build; ls -al; mkdir ../access-art && mv * ../access-art/. && mv ../access-art/* .; aws s3 sync . s3://$BUCKET --delete --acl public-read
